### PR TITLE
0.2 WIP

### PR DESCRIPTION
**Pull request by jamesturk**
very much a work in progress

currently trying to convert each proposed change to a relatively clean diff

### CODE REVIEW

**Comment by migurski** [comment]
Looking good! I notice that the ID field on divisions got lost, but it’s still referenced as `division_id` elsewhere.

**Comment by migurski** [comment]
Also worth noting: @invisiblefunnel has observed that keeping column names identical across tables even when it looks redundant is a huge help when [interacting with GTFS via Pandas](https://github.com/remix/partridge). Would you consider adding back some of that redundancy e.g. `source_*` in the sources table?

**Comment by jamesturk** [comment]
Ah that's a really good point, was mainly trying to enforce consistency but
I'll reverse that and go the other way w/ making things consistent.

**Comment by migurski** [comment]
I’m curious about your use of “OPSRCID:” and other prefixes. I’ve been using [Brooklyn Integers](https://brooklynintegers.com) to generate opaque + unique IDs for PlanScore, and started putting alpha prefixes on to keep everything a string regardless of environment. What are your thoughts on generating IDs?

**Comment by migurski** [comment]
I like your introduction of specific kinds of districts (e.g. House, Assembly, etc.).

**Comment by migurski** [comment]
Also, wondering about overlaps between Open Elections and `VoteTotal` here. Okay to have duplication? Should we link out to them?

**Comment by jamesturk** [comment]
I'm leaning towards unique prefixes to be a bit more user-friendly, as for generation of the ID itself, I'm agnostic between uuid/random integer/etc., but I think if we're adding some kind of prefix it makes sense to differentiate the 4 or so types somewhat.  

re: election data.  Based on what we've heard, we're operating under the assumption we need to pull in a subset of election data for a lot of the apps.  Having that available in a predictable place seems like it'll be key, and I don't think there's a way to do that right now without pulling it in.

**Comment by migurski** [comment]
Makes sense, thanks for the further explanation!

**Comment by jamesturk** [comment]
example in this format is here: https://github.com/OpenPrecincts/Data-Sharing-Schema/tree/va-example/va

cc @maxhully @hwheelen @migurski

**Comment by migurski** [comment]
Awesome! I will give this a close read as soon as I can; probably tonight sometime.

**Comment by migurski** [comment]
…should there be a GeoJSON or SHP file there for the areas?

**Comment by jamesturk** [comment]
ah yes there should! didn't realize it isn't uploaded yet

**Comment by jamesturk** [comment]
(added now)

**Comment by jamesturk** [comment]
Feedback to incorporate:

- alter name of Demographic to reflect other uses
- sources covering chain of custody
- question about Demographic->Shape

**Pull request merged**
